### ISSUE TITLE
Proximity sensor during a call not work on galaxy a52 4g

### ISSUE THREAD

**Issue by ofekdevices** [AndyCGYan/lineage_patches_unified#3]
Hi. i have samsung galaxy a52 4g and i have lineage os 19 and i try 19.1 And both roms the proximity sensor not work during call.
And I was hoping it would be fixed. so AndyCGYan can you pls fix this problem in a rom and gsi ?
Please, I'd be grateful if you did.

Thanks.
OfekDevices.

**Comment by AndyCGYan** [comment]
Quote the XDA thread:

> Must-read:
> You are STRONGLY ADVISED to try [PHH's AOSP](https://github.com/phhusson/treble_experimentations/releases) of equivalent version FIRST and identify/[report](https://github.com/phhusson/treble_experimentations/issues) issues there, before moving onto other GSIs that are based on his work, including this one.
> If you do find bugs on this GSI and want to report, then you MUST try reproducing on AOSP, and ONLY proceed to report here when it's specific to this GSI. This filters out bugs common to all PHH-based GSIs, which you should let PHH know, not me. I might silently ignore your report if you skip this.

**Comment by ofekdevices** [comment]
Okay i understand thenks

**Comment by AndyCGYan** [comment]
No follow-up in 2 weeks, I assume you've found out it's an AOSP thing? Closing.
